version: "3.3"

services:
  box-hg-gateway:
    image: "ci-cd-project-producao:088bca0"
    ports:
      - 8381:8080
    environment:
      - nome.ambiente=Produção
    deploy:
      replicas: 1
     
